### PR TITLE
Minor comment fix + REST Server

### PR DESCRIPTION
**Pull request by ras0219**
I wrote a simple REST server that serves up the LolClient functionality.

I think that a REST interface is much more easily dealt with for integration into other systems than just javascript (currently planning to write a python crawler/scraper off of this).

### CODE REVIEW

**Comment by justinjones** [comment]
Nice work, but I believe there is an issue with node-lol-client (due to the AMF/RTMP stuff) where the connection dies after ~300 requests.

In league of stats I've handled this by basically just reconnecting whenever it times out, but I believe that would cause issues here - it would probably get a new connection event and try to spawn a new http server, which would obviously fail.

We probably want to look at a more robust solution - a single server that spools up whichever regions you want (euw, eune, na) and handles when the lol client connection is down, reconnecting, etc.

**Comment by justinjones** [comment]
I'm still happy to accept this as-is, because this repo is basically YMMV, but if you wanted to look at that reconnect issue and maybe try to handle it in the lol-client itself (auto-reconnect, queue pending requests while disconnected, etc) that would be awesome. Let me know!

**Comment by justinjones** [comment]
Here's some code from node_modules/namf/rtmp.coffee

```
  send: (cmd, cb) ->
    [cmd.id, cmd.type] = [@_nextCallId, (@objectEncoding == 0 and RTMPMessage.RPC or RTMPMessage.RPC3)]
    callId = @_nextCallId
    @_nextCallId += 1

    @_callbacks[callId] = cb
    closeSocket = () =>
      console.log 'Timeout reached, closing socket.'
      if !@broken
        @broken = true
        @socket.destroySoon()
      for key, timeout of @_timeouts
        clearTimeout timeout
    timeoutId = setTimeout closeSocket, 10000
    @_timeouts[callId] = timeoutId

    @writeMessage(cmd.toMessage())
```

Basically after ~300 requests the socket is still connected but it just doesnt receive anymore data. So I capture this by setting a 10sec timeout when a request is made and manually closing the socket if we get no response in 10secs. The timeout is cleared if a response is received as well.

So basically, in this error state the @stream object on the LolClient instance will receive a disconnect and/or error event. So we could just catch that and auto-reconnect, but we would still lose any requests sent during that time unless some sort of queue and replay system is setup.

**Comment by ras0219** [comment]
Yeah, this sounds definitely doable.  On the other hand, waiting 10secs before retrying would be an issue for a web server (I'm thinking maybe reduce the timeout to 5s or even 3s to the lol servers -- I need your advice here on how slow they get during peak times).

If the timeout could be reduced, we could catch it and relaunch the server.

Another thought: Run two clients simultaneously.  Load balance + failover as needed.  You could even keep a running counter and reset the client once you hit 200 reqs.

**Comment by ras0219** [comment]
By the way, excellent job on league of stats. Before I realized you released your client source here, I had run some regex on your pages to do some analysis of my own -- I'm working on doing some further in-depth analysis than you have presented on leagueofstats.

**Comment by justinjones** [comment]
On league of stats, I basically handle it by running two connections to riot for each region like you say (it requires separate accounts for each though)

Regarding the timeout, it could probably be lowered, I think the bigger problem would be your servers bandwidth/CPU load or local connection (during local development) then riot's servers - it's just an SSL socket so it doesn't have a whole lot of overhead.

The better thing would be of course to fix my RTMP code, but I messed with it for hours and couldn't figure out why it's dying. Never used RTMP/AMF before writing this stuff, but I think it's something to do with some sort of ACK message that needs to happen after a certain number of bytes.

**Comment by ras0219** [comment]
It seems like you can't use the summonerId's returned from match history to request information on those summoners. Any thoughts on that?

**Comment by justinjones** [comment]
There is no way to do lookup on summonerId, only acctId.

There is a getSummonerNames function that isn't implemented in
node-lol-client... the packet looks like below, shouldnt be hard for you to
do ;)

Basically takes array of summoner Id's and returns array of names, which
can be used for getSummonerByName

8/5/2011 20:01:13.719 [DEBUG]
com.riotgames.platform.common.utils.RemoteObjectGenerator Sending message:
(mx.messaging.messages::RemotingMessage)#0
  body = (Array)#1
    [0](Array)#2
      [0] #######
      [1] #######
      [2] #######
      [3] #######
      [4] #######
      [5] #######
      [6] #######
      [7] #######
      [8] #######
      [9] #######
      [10] #######
      [11] #######
      [12] #######
  clientId = (null)
  destination = "summonerService"
  headers = (Object)#3
    DSEndpoint = "my-rtmps"
    DSId = "1ED1710D-3B1C-C957-5842-E848B572DA85"
    DSRequestTimeout = 60
  messageId = "A697C038-B28D-F2F6-4E1A-9C64BFF6BE10"
  operation = "getSummonerNames"
  source = (null)
  timestamp = 0
  timeToLive = 0

On Tue, Jun 5, 2012 at 1:38 PM, ras0219 <
reply@reply.github.com

**Comment by justinjones** [comment]
Just an fyi as well, summonerId's and acctId's are not unique across
regions (only within the same region), so if your building some sort of
site to store multiple regions, keep that in mind.

**Comment by ras0219** [comment]
Thanks for the tip.

**Pull request closed without merging**
